<testsuite errors="0" failures="1" name="unittest.suite.TestSuite" tests="1" time="4.643">
  <testcase classname="__main__.qa_add_vector_bb" name="test_001_t" time="4.6427">
    <failure type="exceptions.AssertionError">10 != 0
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "qa_add_vector_bb.py", line 49, in test_001_t
    self.assertFloatTuplesAlmostEqual (expected_result, result_data, 6)
  File "/usr/local/lib/python2.7/dist-packages/gnuradio/gr_unittest.py", line 88, in assertFloatTuplesAlmostEqual
    self.assertEqual (len(a), len(b))
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
    </failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
